# Generated by Django 5.0.3 on 2024-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_council_user_delegation_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gradeLevel', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('cpr', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('additional_data', models.JSONField(default=dict)),
            ],
        ),
    ]
