# Generated by Django 5.0.3 on 2024-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='fullname',
            new_name='fullName',
        ),
    ]
