# Generated by Django 5.0.3 on 2024-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='has_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='padded_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
